### ISSUE TITLE
semin[r] | coding_club - Getting started

### ISSUE THREAD

**Issue by anna-deasey** [StirlingCodingClub/studyGroup#1]
Over the next couple of weeks Coding Clubbers could go through a tutorial about how to get started with GitHub and how the study group works? Below is a link to the Aberdeen Study Group website where they have done this:  

Aberdeen Study Group - How to make a study group - https://aberdeenstudygroup.github.io/studyGroup/lessons/SG-T11-MakeTutorial/MakeTutorial/

If @bradduthie is ok with preparing a topic for the meeting on the Wed 19th Sep, maybe we could start with a discussion about any coding-club/study-group progress and give a chance for people to make changes or offer improvements, before moving on to the next couple of week's topic?

**Comment by bradduthie** [comment]
Sounds like a good idea @anna-deasey -- I can prepare an introduction for 19 SEP to introduce everyone to GitHub (and to a lesser extent, git), then we can take it from there. Happy to see so many participants already joining the group!
