### ISSUE TITLE
Calendar permissions.

### ISSUE THREAD

**Issue by rosemckeon** [StirlingCodingClub/studyGroup#10]
Who has control of the stirlingcodingclub@gmail.com email account? The calendar on the website won't show any events due to permissions.

**Comment by bradduthie** [comment]
@rozeykex That'd be me. I'll send you the password in an email -- do you know how to fix this issue?

**Comment by rosemckeon** [comment]
@bradduthie I think so, I've shared some public calendars before. I'll give it a shot :)

**Comment by rosemckeon** [comment]
@bradduthie sorted.
