### ISSUE TITLE
Has anybody got any advice for working with lat/long data and converting units to/from metres?

### ISSUE THREAD

**Issue by rosemckeon** [StirlingCodingClub/studyGroup#31]
I have a bunch of data with lat/long values, as well as location accuracy (m). I'm trying to plot `lat ~ long` for each data point, with a larger circle around each point showing the location accuracy. So, in effect creating a basic map. But, I'm getting confused with the scales because lat and long are not metric (1 lat = ~111 Km nr the equator). So, ideally, I think I need to convert my location accuracy to the same units as lat/long. Then I could set point size to be defined by that column. Can anybody help?

Here's a snippet to create similar data:

```R
locations <- data.frame(
  lat = c(37.32022, 37.32066, 37.32023, 37.32029, 37.31966, 37.32032),
  long = c(-8.875420, -8.872290, -8.875833, -8.875418, -8.875191, -8.875565),
  location_accuracy = c(5, 3, 6, 3, 5, 3)
 )
```

**Comment by bradduthie** [comment]
I just dug out some of the 10+ year old code from the first or second year of my PhD. You might want to check on how accurate the zone is, and on the library PBSmapping.

The `data` argument should be a data matrix or data frame. The `Lat` and `Lon` should be the columns for the latitude and longitude coordinates in `data`, respectively.

```
#Converts Lat-Lon into UTM.
library(PBSmapping);

LLtoUTM <- function(data,Lat,Lon,km=TRUE){
	dat <- cbind(data[,Lon],data[,Lat]);
	Coo <- as.data.frame(x=dat,rownames=dim(data)[1]);
	zns <- seq(from=-180,to=180,by=6);
	Nor <- seq(from=0,to=80,by=8);
	let <- c("N","P","Q","R","S","T","U","V","W","X");
	mat <- NULL;
	unq <- NULL;
	nor <- NULL;
	for(i in 1:dim(dat)[1]){
		zne <- sum(dat[i,1] > zns);
		nor[i] <- let[sum(dat[i,2] > Nor)];
		mat <- rbind(mat,c(zne,dat[i,]));
		if(sum(unq==zne) == 0){
			unq <- c(unq,zne);	
		}
	}
	ord <- order(x=mat[,1]);
	mat <- mat[ord,];
	br1 <- 0;
	nwz <- NULL;
	for(i in 1:length(unq)){
		br2 <- br1 + sum(unq[i]==mat[,1]);
		nwz[[i]] <- as.matrix(t(mat[(br1+1):br2,]));
		br1 <- br2;
	}
	br1 <- 0;
	nwz <- NULL;
	for(i in 1:length(unq)){
		br2 <- br1 + sum(unq[i]==mat[,1]);
		nmt <- matrix(data=mat[(br1+1):br2,],ncol=3);
		nwz[[i]] <- as.data.frame(nmt);
		colnames(x=nwz[[i]]) <- c("zone","X","Y");
		br1 <- br2;
	}
	utm <- NULL;
	for(i in 1:length(nwz)){
		attr(x=nwz[[i]],which="zone") <- nwz[[i]][1,1];
		attr(x=nwz[[i]],which="projection") <- "LL";
		utm <- rbind(utm,convUL(xydata=nwz[[i]],km=km));
	}
	utm <- utm[order(ord),];
	utm <- cbind(utm[,1],nor,utm[,2:3]);
	colnames(x=utm) <- c("Zone E","Zone N","Easting","Northing");
	rownames(x=utm) <- 1:dim(utm)[1];
	return(utm);
}
```

Let me know if it doesn't work (or if it does!).

**Comment by rosemckeon** [comment]
Thanks @bradduthie! I'll give it a whirl.

**Comment by bradduthie** [comment]
Tried Edinburgh, Belfast, Chicago, and Seoul. It seems to work. You just need to use decimal, and anything West or South should be negative (i.e., lat-lon coordinates of Belfast are Lat: 55.9533, Lon: -3.1883).

**Comment by rosemckeon** [comment]
Looks like this works great @bradduthie! Not tried plotting yet but the conversion runs nicely.
________________________________

**Comment by bradduthie** [comment]
Glad it works @rosemckeon -- looking at it now, you might need to tweak it again if you're doing anything in the Southern Hemisphere. Otherwise, I think it should be fine.

**Comment by rosemckeon** [comment]
@bradduthie All my coordinates are for Portugal, but I'll bear that in mind for the future!
________________________________

**Comment by rosemckeon** [comment]
(email reply is weird)
